package com.xstv.desktop.app.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig itemInfoDaoConfig;

    private final ItemInfoDao itemInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        itemInfoDaoConfig = daoConfigMap.get(ItemInfoDao.class).clone();
        itemInfoDaoConfig.initIdentityScope(type);

        itemInfoDao = new ItemInfoDao(itemInfoDaoConfig, this);

        registerDao(ItemInfo.class, itemInfoDao);
    }
    
    public void clear() {
        itemInfoDaoConfig.getIdentityScope().clear();
    }

    public ItemInfoDao getItemInfoDao() {
        return itemInfoDao;
    }

}
